const state={data:null,view:'overview'};
const $=(s)=>document.querySelector(s);const money=n=>new Intl.NumberFormat('zh-TW',{maximumFractionDigits:0}).format(n||0);const pct=n=>`${n>=0?'+':''}${Number(n||0).toFixed(2)}%`;
function nav(){document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');location.hash=b.dataset.view})}
function strategies(){const colors={P19:'#45e0d2',P35:'#b8f06a',P40:'#ffbd59'};$('#strategy-cards').innerHTML=state.data.strategies.map(s=>`<article class="strategy-card" style="--accent:${colors[s.code]}"><div class="strategy-top"><span class="strategy-code">${s.code}</span><span class="strategy-status">${s.status}</span></div><h3>${s.name}</h3><div class="strategy-rule">${s.rule}</div><div class="metrics"><div class="metric"><small>歷史報酬</small><b class="positive">${pct(s.return_pct)}</b></div><div class="metric"><small>最大回撤</small><b class="negative">${pct(s.max_drawdown_pct)}</b></div><div class="metric"><small>平倉勝率</small><b>${pct(s.win_rate_pct)}</b></div></div></article>`).join('')}
function miniHoldings(){const rows=state.data.stocks.slice(0,7);$('#overview-holdings').innerHTML=`<div class="mini-list">${rows.map(x=>`<div class="mini-row"><b>${x.stock}</b><span>${x.name} · ${x.plans.join(' / ')}</span><strong>${Number(x.score).toFixed(1)}</strong></div>`).join('')}</div>`}
function stockCards(filter=''){const q=filter.trim().toLowerCase();const rows=state.data.stocks.filter(x=>`${x.stock}${x.name}`.toLowerCase().includes(q));$('#stock-grid').innerHTML=rows.length?rows.map(x=>`<article class="stock-card"><div class="stock-head"><div><div class="stock-code">${x.stock}</div><div class="stock-name">${x.name}</div></div><div class="score-ring" style="--score:${Math.min(100,x.score)}"><b>${Number(x.score).toFixed(1)}</b></div></div><div class="detail-list"><div class="detail"><span>策略</span><b>${x.plans.join(' / ')}</b></div><div class="detail"><span>訊號日期</span><b>${x.signal_date}</b></div><div class="detail"><span>模型市值</span><b>${money(x.market_value)}</b></div><div class="detail"><span>9359訊號日</span><b class="${x.broker_9359_amount>0?'positive':''}">${money(x.broker_9359_amount)}</b></div><div class="detail"><span>登錄年齡</span><b>${x.listing_age??'—'}</b></div></div><div class="broker-chips">${x.brokers.map(b=>`<span class="chip">${b.code} · w${b.weight}</span>`).join('')}</div></article>`).join(''):`<div class="banner">找不到符合的股票。</div>`}
function brokerRows(filter=''){const q=filter.trim().toLowerCase();const rows=state.data.brokers.filter(x=>`${x.code}${x.name}`.toLowerCase().includes(q));$('#broker-rows').innerHTML=rows.map(x=>`<tr><td class="rank">#${x.rank}</td><td><b>${x.code}</b><br><small>${x.name}</small></td><td>${Number(x.weight).toFixed(1)}</td><td><b>${(x.quality*100).toFixed(1)}</b><div class="bar"><i style="width:${x.quality*100}%"></i></div></td><td>${(x.win_rate*100).toFixed(1)}%</td><td>${x.mature_labels}</td><td>${(x.return_score*100).toFixed(2)}%</td></tr>`).join('')}
function featuredBrokers(){$('#featured-brokers').innerHTML=state.data.featured_brokers.map(x=>`<article class="strategy-card" style="--accent:#ffbd59"><div class="strategy-top"><span class="strategy-code">重點追蹤 · ${x.code}</span><span class="strategy-status">${x.roster_status}</span></div><h3>${x.name}</h3><div class="strategy-rule">${x.role}</div><div class="metrics"><div class="metric"><small>P19依據</small><b>${x.p19_basis}</b></div><div class="metric"><small>P35依據</small><b>${x.p35_basis}</b></div><div class="metric"><small>注意</small><b>${x.caveat}</b></div></div></article>`).join('')}
function method(){const f=state.data.formula;$('#formula-grid').innerHTML=f.stock_score.map(x=>`<div class="formula"><b>${x.points}</b><span>${x.name}</span><small>${x.detail}</small></div>`).join('');$('#money-tiers').innerHTML=f.money_tiers.map(x=>`<div class="money-tier"><b>+${x.points}</b><small>≥ ${x.amount}</small></div>`).join('');$('#limitations').innerHTML=state.data.limitations.map(x=>`<li>${x}</li>`).join('')}
async function init(){nav();try{const r=await fetch('data/dashboard.json',{cache:'no-store'});if(!r.ok)throw Error(r.status);state.data=await r.json();$('#asof').textContent=`資料 ${state.data.as_of}`;$('#status-banner').innerHTML=`<b>雙軌紙上追蹤：</b> P19與P35各自以30萬元現金開始。資料截止日以前的模型持股只供觀察；目前狀態為 <strong>${state.data.paper_status}</strong>。`;strategies();miniHoldings();stockCards();featuredBrokers();brokerRows();method();$('#stock-search').oninput=e=>stockCards(e.target.value);$('#broker-search').oninput=e=>brokerRows(e.target.value);const hash=location.hash.slice(1);if(hash&&$(`[data-view="${hash}"]`))$(`[data-view="${hash}"]`).click()}catch(e){$('#status-banner').textContent='資料載入失敗，請確認 data/dashboard.json 已部署。'}}init();
