function renderChampion(data){
 const c=data.champion;if(!c)return;
 const el=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
 const number=n=>Number(n).toLocaleString('zh-TW',{maximumFractionDigits:0}),percent=n=>`${Number(n)>=0?'+':''}${Number(n).toFixed(2)}%`;
 const reason=r=>({admit:'共同新建倉・評分與容量合格',research_support30:'原建倉者庫存低於高點70%・連續2日',distribution:'分數低於40且連續2日加權淨賣',emerging_last_close_settlement:'轉板結算'}[r]||(r.startsWith('replace:')?'分差換股 → '+r.slice(8):r));
 const old=(Date.now()-Date.parse(c.as_of+'T00:00:00+08:00'))/86400000>4;
 el('champion-status').textContent=`模型資料 ${c.as_of}｜${old?'資料落後，暫停依此建立新委託；請等待更新。':'依最新可用官方資料重播，請先核對日期再操作。'} 其他策略日期請看各頁標示。`;el('champion-status').classList.toggle('data-warning',old);
 el('champion-metrics').innerHTML=[['模型淨值',number(c.account.equity)+'元'],['累積報酬',percent(c.summary.return_pct)],['最大回撤',percent(c.summary.max_drawdown_pct)],['持股／現金',c.account.positions+'檔 / '+number(c.account.cash)+'元']].map(([k,v])=>`<div><small>${k}</small><b>${v}</b></div>`).join('');
 const orderCard=(o,pending=false)=>`<details class="order-card"><summary><strong class="${o.side==='buy'?'buy-label':'sell-label'}">${o.side==='buy'?'↑ 買進':'↓ 賣出'}</strong> ${esc(o.stock)} ${esc(c.names[o.stock]||'')}<br><small>決策 ${esc(o.signal_date)} · ${pending?'待執行／持續等待':o.fills?.length?'有模型成交':'未有成交'}</small></summary><p>${esc(reason(o.reason))}</p><p>${o.side==='buy'?'預算上限 '+number(o.budget)+' 元':'委託股數 '+(o.quantity?number(o.quantity):'退出剩餘部位')}；最早決策日的下一市場交易日。</p>${(o.fills||[]).map(f=>`<p>${esc(f.date)}：${number(f.shares)} 股 × ${Number(f.price).toFixed(2)}元</p>`).join('')}${(o.attempts||[]).map(a=>`<p>${esc(a.date)}：${esc(({filled:'完成',partial:'部分成交',no_quote:'無可用行情',no_slot:'無空席',no_capacity:'容量不足',no_cash:'資金不足'})[a.status]||a.status)}</p>`).join('')}</details>`;
 el('champ-pending').innerHTML=c.pending.length?c.pending.map(p=>orderCard(p,true)).join(''):'<div class="banner">最新資料日沒有待執行指令。等待下一次評分；不代表每天都需要買賣。</div>';
 el('champ-holdings').innerHTML=c.holdings.map(h=>`<article class="stock-card"><div class="stock-code">${esc(h.stock)} · ${esc(h.name)}</div><h2>${percent(h.return_pct)}</h2><p>未實現 ${number(h.pnl)}元</p><div class="detail-list">${[['持股',number(h.shares)+'股'],['成本／現價',h.avg_cost.toFixed(2)+'／'+h.mark.toFixed(2)],['市值',number(h.market_value)+'元'],['進場',h.entry_date],['持有',h.holding_sessions+'交易日／'+h.calendar_days+'曆日'],['分數',h.score.toFixed(1)]].map(([k,v])=>`<div class="detail"><span>${k}</span><b>${v}</b></div>`).join('')}</div>${h.stale_sessions?'<p>估值行情落後 '+h.stale_sessions+'交易日</p>':''}</article>`).join('')||'<p>目前留現金。</p>';
 el('champ-date').innerHTML='<option value="all">所有日期（最新優先）</option>'+c.dates.map(d=>`<option>${d}</option>`).join('');
 function history(){const date=el('champ-date').value,side=el('champ-side').value,orders=c.orders.filter(o=>(date==='all'||o.signal_date===date)&&(side==='all'||o.side===side));el('champ-count').textContent=`${orders.length}筆決策・點擊卡片查看成交及原因`;el('champ-orders').innerHTML=orders.map(o=>orderCard(o)).join('')||'<div class="banner">此篩選沒有紀錄。</div>'}
 el('champ-date').onchange=history;el('champ-side').onchange=history;history();
 document.querySelectorAll('[data-champ]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-champ]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('.champ-pane').forEach(x=>x.hidden=x.id!=='champ-'+b.dataset.champ)});
}
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);const b=[...document.querySelectorAll('nav button[data-view]')].find(x=>x.dataset.view===id);if(b&&!b.classList.contains('active'))b.click()});
