const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 for(const width of [360,390,768,1440]){
  const page=await browser.newPage({viewport:{width,height:844},isMobile:width<700,hasTouch:width<700});
  const errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await page.goto((process.env.Q8_TEST_URL||'http://127.0.0.1:8765/')+'#champion');
  await page.locator('#site-password').fill(process.env.Q8_PASSWORDS.split(';')[0]);await page.locator('#unlock-form button').click();
  await page.locator('#champion.active').waitFor();await page.locator('#champion-metrics b').first().waitFor();
  if(await page.locator('#champ-account').inputValue()!=='paper')throw Error('New cash account must be default');
  if(!(await page.locator('#champion-metrics').innerText()).includes('100,000'))throw Error('Missing 100k capital');
  await page.locator('#review-plan').click();
  if(!(await page.locator('#plan-feedback').innerText()).includes('已閱讀'))throw Error('Review feedback missing');
  if(width===390)await page.screenshot({path:'site-mobile-preview.png',fullPage:true});
  await page.locator('#champ-account').selectOption('model');
  await page.locator('[data-champ="hold"]').click();await page.locator('#champ-hold:not([hidden])').waitFor();
  const holdings=await page.locator('#champ-holdings .stock-card').count();
  await page.locator('[data-champ="history"]').click();await page.locator('#champ-side').selectOption('sell');
  await page.locator('#champ-orders details').first().locator('summary').click();
  if(!await page.locator('#champ-orders details').first().getAttribute('open').then(x=>x!==null))throw Error('Expand failed');
  const count=await page.locator('#champ-count').innerText();
  await page.locator('#champ-date').selectOption({index:1});
  await page.locator('[data-champ="rules"]').click();
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
  if(errors.length||overflow)throw Error(JSON.stringify({width,errors,overflow}));
  await page.locator('[data-champ="action"]').click();
  await page.locator('#champ-account').selectOption('paper');
  console.log(JSON.stringify({width,holdings,count,errors,overflow}));await page.close();
 }await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
